export type AuditAction = 
  | 'AUTH_LOGIN'
  | 'AUTH_LOGOUT'
  | 'AUTH_PASSWORD_RESET'
  | 'ADMIN_FACULTY_CREATED'
  | 'ADMIN_FACULTY_UPDATED'
  | 'ADMIN_FACULTY_ARCHIVED'
  | 'ADMIN_DEPARTMENT_CREATED'
  | 'ADMIN_DEPARTMENT_UPDATED'
  | 'ADMIN_DEPARTMENT_ARCHIVED'
  | 'ADMIN_PROGRAM_CREATED'
  | 'ADMIN_PROGRAM_UPDATED'
  | 'ADMIN_PROGRAM_ARCHIVED'
  | 'ADMIN_COURSE_CREATED'
  | 'ADMIN_COURSE_UPDATED'
  | 'ADMIN_COURSE_ARCHIVED'
  | 'ADMIN_USER_ROLE_CHANGED'
  | 'ADMIN_USER_ACTIVATED'
  | 'ADMIN_USER_DEACTIVATED'
  | 'COURSE_REGISTRATION_SUBMITTED'
  | 'COURSE_REGISTRATION_APPROVED'
  | 'COURSE_REGISTRATION_REJECTED'
  | 'GRADE_CHANGED'
  | 'LIVE_CLASS_SCHEDULED'
  | 'LIVE_CLASS_CANCELED'
  | 'RECORDING_PUBLISHED'
  | 'RECORDING_UNPUBLISHED'
  | 'FILE_UPLOADED'
  | 'FILE_DELETED'
  | 'ANNOUNCEMENT_CREATED'
  | 'ANNOUNCEMENT_PUBLISHED'
  | 'ANNOUNCEMENT_UNPUBLISHED'
  | 'DISCUSSION_MODERATED'
  | string; // allow others as string

export interface AuditLogPayload {
  universityId: string;
  userId?: string;
  action: AuditAction;
  entityType: string;
  entityId?: string;
  metadata?: Record<string, any>;
  ipAddress?: string;
}
